---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wkndr
  labels:
    app: wkndr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wkndr
  template:
    metadata:
      labels:
        app: wkndr
    spec:
      volumes:
      - name: chroot-home
        hostPath:
          path: /var/tmp/chroot-home
          type: DirectoryOrCreate
      containers:
      - name: wkndr
        image: wkndr:latest
        imagePullPolicy: IfNotPresent
        command: ["/var/lib/wkndr/release/wkndr.mruby", "--server=/var/lib/wkndr/public", "--no-client"]
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: 100M
            cpu: 200m
          requests:
            memory: 100M
            cpu: 100m
        volumeMounts:
        - name: chroot-home
          mountPath: /var/tmp/chroot/home

---
apiVersion: v1
kind: Service
metadata:
  name: wkndr-service
spec:
  type: NodePort
  selector:
    app: wkndr
  ports:
  - protocol: TCP
    name: app
    port: 8000
    nodePort: 31041

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wkndr-computer-vhost
  annotations:
    ingress.class: wkndr
spec:
  rules:
  - host: wkndr.computer
    http:
      paths:
      - backend:
          serviceName: wkndr-service
          servicePort: 8000
