#!/usr/bin/env ruby


@plain_workflow = Plan.new
@plain_workflow.add_circleci_job("bootstrap", [{"image"=>"polly:latest"}], [{"run"=>{"name"=>"bootstrap", "command"=>"bin/polly build Dockerfile"}}], {"BUNDLE_PATH" => "~/vendor/bundle"}, "/home/app/current")
