#!/usr/bin/env ruby

class WkndrExample < Wkndr
  def default
    server = continous
    
    server.loop("window", 512, 512, 60) { |gl|
      log! :loop

      gl.lookat(0, 0.0, 500.0, 0.0, 0.0, 0.0, 0.01, 200.0)

      gl.play { |global_time, delta_time|
        gl.drawmode {
          gl.twod {
            gl.button(0.0, 0.0, 250.0, 20.0, "start #{global_time}") {
              #TODO: onclick
              log! :click
            }
          }
        }
      }
    }

    show! server
  end
end

WkndrExample.start(ARGV)
