workflows:
  version: 2
  build:
    jobs:
      - package-container
      - one:
          requires:
            - package-container
      - two:
          requires:
            - package-container
      - three:
          requires:
            - package-container


defaults: &defaults
  working_directory: /home/app/current
  environment: &environment_defaults
    FOO: "bar"
  docker:
    - image: &build_image wkndr:latest

version: 2
jobs:
  package-container:
    <<: *defaults
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: bundle and test
          command: |
            set -e

            cd /var/lib/wkndr

            bundle
            bundle exec rake

            wkndr help

  one:
    <<: *defaults
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: foo
          command: |
            env

  two:
    <<: *defaults
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: foo
          command: |
            env

  three:
    <<: *defaults
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: foo
          command: |
            env
