#!/bin/sh
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, rename this file to "post-update".

set -e
set -x

echo post-update... "${1}"

#git checkout "${1}"
git symbolic-ref HEAD "${1}"
git update-server-info

wkndr kaniko "${1}"

echo ... post-update
