#!/bin/sh
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, rename this file to "post-update".

set -e
set -x

trap 'kill -INT $(jobs -lp) 2>/dev/null || true' EXIT

echo post-update... "${1}"

#git checkout "${1}"

if git show-ref "${1}"
then
  git symbolic-ref HEAD "${1}"
  git update-server-info

  if [ "refs/tags/wkndr/build" = "${1}" ];
  then
    wkndr kaniko "${1}"
  elif [ "refs/tags/wkndr/test" = "${1}" ];
  then
    TMPCHECKOUT=$(mktemp -d)/$(basename $(pwd))
    git clone -l . ${TMPCHECKOUT}
    cd ${TMPCHECKOUT}
    unset GIT_DIR
    wkndr test
    export GIT_DIR="."
  else
    echo ...
  fi
fi

echo ... post-update
