#!/bin/sh
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, rename this file to "post-update".

set -e
set -x

echo post-update... $1 $2 $3

git update-server-info

wkndr kaniko

echo ... post-update
