#!/bin/sh
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, rename this file to "post-update".

set -e
set -x

echo update ... $1 $2 $3

echo ... update
