---
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/docker-registry
  delete:
    enabled: true
http:
  addr: :5000
  tls:
    certificate: /etc/ssl/private/registry.wkndr.pem
    key: /etc/ssl/private/registry.wkndr.key
    #clientcas:
    #  - /path/to/ca.pem
    #  - /path/to/another/ca.pem 
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
...
